#!/bin/bash

set -e

MAKE_RESULTS=()

ROOT_PATH=$(cd "$(dirname -- "$0")"; pwd)
BUILD_PATH="$ROOT_PATH/build"
SCRIPTS_PATH="$ROOT_PATH/scripts"

mkdir -p "$BUILD_PATH"

source "$ROOT_PATH/steps"

if [ -z "$PREFIX" ]; then
    export PREFIX="$HOME/.local"
fi

make_sysroot_dirs() {
    local path="$1"

    mkdir -p "$path"
    mkdir -p "$path/bin"
    mkdir -p "$path/include"
    mkdir -p "$path/lib"
    mkdir -p "$path/usr"
    mkdir -p "$path/usr/bin"
    mkdir -p "$path/usr/include"
    mkdir -p "$path/usr/lib"
}

run_command_script() {
    local command="$1"
    local source_name="$2"

    if [ "$source_name" = "global" ]; then
        cd "$ROOT_PATH"
    else
        mkdir -p "$BUILD_PATH/${source_name}"
        cd "$BUILD_PATH/${source_name}"
    fi

    if [ -f "$BUILD_PATH/.$source_name.${command}stamp" ]; then
        MAKE_RESULTS+=("$source_name $command: \033[1;34mSkipped\033[0m")
    elif [ -f "$SCRIPTS_PATH/${source_name}-${command}.sh" ]; then
        echo "Running script $SCRIPTS_PATH/${source_name}-${command}.sh..."
        source "$SCRIPTS_PATH/${source_name}-${command}.sh"
        touch "$BUILD_PATH/.$source_name.${command}stamp"
        MAKE_RESULTS+=("$source_name $command: \033[1;32mDone\033[0m")
    else
        echo -e "\033[1;31mError: Shell script $SCRIPTS_PATH/${source_name}-${command}.sh is not found.\033[0m"
        return 1
    fi

    return 0
}

show_results() {
    for result in "${MAKE_RESULTS[@]}"; do
        echo -e "$result"
    done
}

make_sysroot_dirs "$PREFIX"

for step in "${MAKE_STEPS[@]}"; do
    args=()
    for arg in $step; do
        args+=("$arg")
    done
    source_name="${args[0]}"
    command="${args[1]}"
    source_url="${args[2]}"

    if [ "$command" = "fetch" ]; then
        download_tarball    "$source_name" "$source_url"
        extract_source      "$source_name"
    else
        run_command_script  "$command"  "$source_name"
    fi
done

show_results
